#!/bin/bash
#SBATCH -J mySort           # job name
#SBATCH -o mympi.o%j       # output and error file name (%j expands to jobID)
#SBATCH -n 64              # total number of mpi tasks requested
#SBATCH -p development     # queue (partition) -- normal, development, etc.
#SBATCH -t 00:02:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=wzahhq9@gmail.com
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes
ibrun ./sort.out              # run the MPI executable named a.out
